### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#1]
I know that it was not brought up, but we are going to need to have a better way to explain to the players the control of the games.
Suggestions:
- Tutorial level
- Instruction page

**Comment by HopscotchNinja** [comment]
I will be implementing a bit of a redesign for the first level, and Kane will be creating a script for GUI pop-ups that inform the player about the "F" and "Spacebar" abilities.

**Comment by vivski21** [comment]
Christina, you are making wonderful signs for the player to follow and I was wondering if you can continue that with the other player control and possible actions.
