### ISSUE TITLE
Player Collidor

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#19]
The box collider of the player is above the prefab.
This is a problem since the button reacts to the collider and the action of it causes for it to act unnaturally to what the gamer should see

**Comment by HopscotchNinja** [comment]
This is to do with the UI item Kane attached to the player. It was triggering the button's collider ahead or behind of the player. I have now removed that collider, as Kane doesn't need it for the UI pop-up, which will be better assigned to non-player objects.
