### ISSUE TITLE
Space bar

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#2]
We need to discuss what the space bar should be used for - jumping or detaching?
This is one of the issues some of the participants of our playtest were facing.

**Comment by HopscotchNinja** [comment]
Spacebar is fine for now. I have commented on the wiki that this is actually an effective way of immediately allowing the player to learn what the detach mechanic is, and initially can create some humour that is thematic to the narrative of a robot that has already fallen apart. We will be using a GUI pop-up to indicate this control option in the game.
