### ISSUE TITLE
Player Movement in Pipe

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#20]
The player is able to roll up when he is sliding diagonally on the pipe in level one.

**Comment by HopscotchNinja** [comment]
I have made the slope steeper to account for this. The player controller uses ground colliders optimised for normal platforms and climbing diagonals. I have made the slope vertical for now, but if we do want to have steep diagonal walls for some reason later, I can either make adjustments to the player character, or invisible walls to account for the slope.
