### ISSUE TITLE
Overworld Wiki

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#22]
The description of the Overworld is quite complicated and really confusing.
Trying to visualise it in my head and will show you some ideas I have sketched out.
If possible, try and break down that part of the page into different sections.
I.e. Make a subheading about the background, a subheading about the icons and so on.

**Comment by HopscotchNinja** [comment]
I drew a sketch of the design above the words. Imagine that the buildings and ground are all coloured black.
