### ISSUE TITLE
Attach key

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#3]
The game does not give the player a choose to attach if they wish. This should change as some of the playtesters got slightly frustrated when they had to pass by the body parts and it attached to the player instantly.

**Comment by HopscotchNinja** [comment]
The player will now only be able to attach to another piece when they are not grounded. This will allow them to press the "w" key to attach while in front of the components or land on components for immediate attachment.
You will also be able to move through components if you do not jump once I'm done.
