### ISSUE TITLE
PlayerSpawner

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#31]
Something about the Player Spawn does not seem to work correctly.
There are two different types of player spawners, one in the character folder of the prefab and the other is inside the characterspawns folder. In the prefab of the player spawn, it does not move at all. The other player spawn sort of works, but the head doesn't jump and the different configurations is unresponsive.

**Comment by HopscotchNinja** [comment]
Make sure that the game manager is also in the scene. Close this if that fixes it, and let me know the first error in the debug log (if there are any) for future issues.

**Comment by vivski21** [comment]
Checked it, the player head moves, but the configuration setup does not seem to do anything.

**Comment by vivski21** [comment]
Solved
