### ISSUE TITLE
Time Button

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#32]
Rotating the door disorientates and changes the appearance of the actual object.

**Comment by HopscotchNinja** [comment]
Are to using the correct doors? They should be in the Prefabs > Environment > Activatable folder.

I have tried to replicate this but haven't been able to do so.

**Comment by vivski21** [comment]
I was using the green timer button, it happens when you move the sliding door to a different location and then try to rotate it.

**Comment by vivski21** [comment]
The Button has an activates void where you can link the sliding door into it.
