### ISSUE TITLE
Groundbreaker Legs

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#34]
The Prefab ground breaker legs does not appear in the scene on Unity.

**Comment by HopscotchNinja** [comment]
Is this because you don't have the game manager in scene?

**Comment by vivski21** [comment]
I have added the game manager into the scene, the groundbreaker legs still do not seem to appear.

**Comment by HopscotchNinja** [comment]
On Tuesday I gave a brief explanation of how the new legs work in the scene. Delete that prefab, drag in the generic legs prefab from the character prefabs folder, and in the drop-down box available on its script, choose groundbreaker legs.

**Comment by vivski21** [comment]
It is still invisible.

**Comment by vivski21** [comment]
The groundbreaker legs appear when you are using the normal legs in the character folder of the prefabs.
