### ISSUE TITLE
Attach/Detach action

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#4]
Playtesters have commanded that the attach and detach action plays too fast. Maybe have an animation of the body part coming together or apart to slow it down. Does not need to be a long animation, just something to play out so that the player can see what is happening.

**Comment by HopscotchNinja** [comment]
When the player moves to attach, they will always have some motion as they will have to be ungrounded. On Trigger Enter, the player will either Lerp to the position, or have a gravity replacement force applied with a snap at the end. This will disable control briefly, but make the connection look much smoother.
