### ISSUE TITLE
Gyre Robot

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#42]
The issue is that when the Grye collides with any body part of the robot (legs/arms), the Grye does not go to the opposition direction and simply stops as there is nothing in the way. As soon as the player gets those parts, they die since the Grye is still moving in that direction. As a result of this level 3 is somewhat impossible to complete. -working on.

**Comment by vivski21** [comment]
There is now a new issue that when the player falls on the Gyre with the Ground breaker legs attached, the Grye robot does not destroy and instead kills the player.

**Comment by BIGBOSSKANE** [comment]
Fixed, Gyres now flip on collision with bodyparts
