### ISSUE TITLE
Character and camera movement

### ISSUE THREAD

**Issue by vivski21** [BIGBOSSKANE/Body_Builder_Game#5]
This is the section that the players had most problems with.
Firstly, the character moves too fast and his jumps are either too high or can be manipulated with the environment to gain a higher jump. In other words, it is not natural and takes them out of the game.
Secondly, the camera does not move that smoothly, some of the playtesters stated that it is a little jarring.

**Comment by HopscotchNinja** [comment]
The issue with the camera is largely based on the movement of the player. In the playtest, I wanted to see how far we could push the mobility, as it was the primary reason for the leg components.
The levels were clearly too high, so I have already fixed this. Now the player moves slower with legs and has a lower vertical jump. This has improved the controllability and camera experience at least in the testing I have done. The ledge bouncing still has not been fixed. It is not a priority at this stage and I will get to it eventually if I have time. (A new Issue has been created for it).
